import os, shutil, glob
ROOT = os.path.dirname(os.path.abspath(__file__))
B = os.path.join(ROOT, "build")
OUT = os.path.abspath(os.path.join(ROOT, "..", "..", "teaching-pack"))
plan = {
 "00-INSTRUCTOR": [("build/00-INSTRUCTOR/*.docx", None),
                   ("build/00-INSTRUCTOR/*.txt", None)],
 # The brand kit ships as the zip students receive; no unzipped copy in the repo.
 "01-BRAND-KIT":  [("build/ACMEJOB-brand-kit.zip", None)],
 "02-M01-first-day": [("build/M01/*.docx", None), ("build/M01/*.pptx", None)],
 "03-M02-measurement": [("build/M02/*.docx", None), ("build/M02/*.pptx", None), ("build/M02/*.csv", None)],
 "04-M03-hallucination": [("build/M03/*.docx", None), ("build/M03/*.pptx", None)],
 "05-CHARTS": [("build/charts/*.png", None)],
 "06-BRIDGE": [("bridge/*", None)],
}
# Only replace folders generated by this M01–M03 build. Later teaching-pack
# folders (for example Case B / HW1B) are independent and must survive rebuilds.
os.makedirs(OUT, exist_ok=True)
for folder in plan:
    generated = os.path.join(OUT, folder)
    if os.path.exists(generated):
        if folder == "00-INSTRUCTOR":
            # This folder also contains hand-authored HTML briefings and the
            # run-of-day desk. Replace only this build's generated files so a
            # routine pack rebuild cannot erase those instructor pages.
            for pattern, _ in plan[folder]:
                for source in glob.glob(os.path.join(ROOT, pattern)):
                    target = os.path.join(generated, os.path.basename(source))
                    if os.path.isfile(target):
                        os.remove(target)
        else:
            shutil.rmtree(generated)
n=0
for folder, items in plan.items():
    dst = os.path.join(OUT, folder); os.makedirs(dst, exist_ok=True)
    for pat, sub in items:
        src = os.path.join(ROOT, pat)
        if sub:
            shutil.copytree(src, os.path.join(dst, sub)); n += sum(len(f) for _,_,f in os.walk(src))
        else:
            for f in sorted(glob.glob(src)):
                shutil.copy(f, dst); n += 1
print(f"{n} files")
for r, dirs, files in sorted(os.walk(OUT)):
    rel = os.path.relpath(r, OUT)
    if rel.startswith("01-BRAND-KIT/unzipped") and rel != "01-BRAND-KIT/unzipped": continue
    if rel != ".": print(f"\n{rel}/")
    for f in sorted(files): print(f"   {f}")
