#!/usr/bin/env python3
"""Generate the SEIS 201 Unit 1 HW Case B lift-station artifacts.

All organizations, people, equipment, specifications, and measurements in this
case are fictional. Values are instructional and are not verified by a licensed
engineer.

The deterministic seed is intentionally documented so instructors can reproduce
the student data and answer key exactly.
"""

from __future__ import annotations

import csv
import random
import statistics
from datetime import datetime, timedelta
from pathlib import Path


SEED = 201_01_07
READINGS_PER_CHANNEL = 12
BASELINE_PSIG = 42.00
TOLERANCE_PSIG = 0.75
PLANTED_CHANNEL = "PT-107"
PLANTED_OFFSET_PSIG = 4.80
CHANNELS = [f"PT-{channel}" for channel in range(101, 109)]

ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = ROOT / "teaching-pack" / "07-HW-CASE-B-LIFT-STATION"
STUDENT_DIR = OUTPUT_DIR / "student"
INSTRUCTOR_DIR = OUTPUT_DIR / "instructor"


def generate_readings() -> dict[str, list[float]]:
    rng = random.Random(SEED)
    readings: dict[str, list[float]] = {}
    for channel in CHANNELS:
        center = BASELINE_PSIG
        if channel == PLANTED_CHANNEL:
            center += PLANTED_OFFSET_PSIG
        readings[channel] = [
            round(rng.gauss(center, 0.07), 2)
            for _ in range(READINGS_PER_CHANNEL)
        ]
    return readings


def write_csv(readings: dict[str, list[float]]) -> None:
    start = datetime(2028, 9, 16, 10, 20)
    path = STUDENT_DIR / "sensors_startup.csv"
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            ["channel_id", "reading_index", "value", "units", "timestamp"]
        )
        for index in range(READINGS_PER_CHANNEL):
            timestamp = start + timedelta(seconds=30 * index)
            for channel in CHANNELS:
                writer.writerow(
                    [
                        channel,
                        index + 1,
                        f"{readings[channel][index]:.2f}",
                        "psig",
                        timestamp.isoformat(timespec="seconds"),
                    ]
                )


def write_foreman_report(grand_average: float) -> None:
    deviation = grand_average - BASELINE_PSIG
    report = f"""# ACMEJOB.Ai | FOREMAN v4.2

## Automated startup acceptance report

**Client:** Westfield Public Works  
**Facility:** Oak Street Lift Station  
**System:** Force-main / wet-well discharge header pressure instrumentation  
**Run:** Standby equalization check, 2028-09-16  
**Result:** **PASS**

FOREMAN v4.2 processed 96 pressure observations from eight installed
transducers. The grand average was **{grand_average:.2f} psig**, a deviation of
**{deviation:+.2f} psig** from the expected 42.00 psig standby baseline.

Acceptance limit: ±0.75 psig per WP-LS-3 §2.1. Because the reported deviation is
within ±0.75 psig, the instrument set is accepted for startup.

No per-channel exception table was generated.

---

**AUTOMATED DISPOSITION: PASS**  
Generated by FOREMAN v4.2 for ACMEJOB.Ai

Training artifact only. WP-LS-3 is fictional. Invented data; not verified by a
licensed engineer.
"""
    (STUDENT_DIR / "FOREMAN_PASS_report.md").write_text(report, encoding="utf-8")


def write_startup_note() -> None:
    note = """# ACMEJOB.Ai

## Oak Street Lift Station — instrument installation / startup note

**Client:** Westfield Public Works  
**Work order:** OSL-28-0916  
**Date:** 2028-09-16  
**Prepared by:** Wes Tanaka, EIT  
**Reviewed by:** Pending Diane Halvorsen, PE  
**Status:** Field draft — not PE-verified

### Purpose and standby condition

Eight pressure transducers, PT-101 through PT-108, were installed on the common
force-main / wet-well discharge header. Startup observations were recorded with
both pumps off, discharge isolation valves seated, and the instrument manifold
equalization valves open. The header was allowed to settle for ten minutes.

The expected pressure in this defined standby condition is 42.00 psig.
Fictional project specification WP-LS-3 §2.1 states:

> Under the defined no-flow standby condition, each discharge-pressure channel
> shall read within ±0.75 psig of the expected baseline before acceptance.

### Field checklist

| Item | Field entry |
|---|---|
| Tag and cable labels | PT-101 through PT-108 matched PLC inputs AI-01 through AI-08. |
| Manifold position | Equalization valves marked open at data capture. |
| Loop power | 24 VDC supply steady; no PLC diagnostic flags. |
| Reference | Header test gauge showed 42.0 psig after settling. |
| Weather / access | Indoor dry well, 21 °C; access clear. |
| Data capture | Twelve rounds at 30-second spacing exported for FOREMAN review. |

### Technician notes

- PT-103 conduit label was replaced after the original sleeve tore.
- AI-05 took one extra scan to appear after the PLC rack restart.
- During the earlier point-to-point check, PT-107 would not settle while its
  equalization valve was shut. J.M. used the local zero trim (+4.8 psi shown
  as the correction) to finish PLC scaling; the valve was then reopened.
  Revisit after lunch if startup timing permits.
- Temporary test leads were removed from the terminal cabinet.
- No leakage was visible at the impulse tubing fittings.

### Handoff

FOREMAN v4.2 was asked to evaluate the exported standby readings against
WP-LS-3 §2.1. Diane's engineering acceptance and signature remain outstanding.

---

**SCHEMATIC / INSTRUCTIONAL DATA ONLY.** Westfield Public Works, Oak Street Lift
Station, WP-LS-3, and all measurements are fictional. This field draft is not
verified by a licensed engineer and is not suitable for construction, operation,
or public-safety decisions.
"""
    (STUDENT_DIR / "install_startup_note.md").write_text(note, encoding="utf-8")


def write_student_ask() -> None:
    handout = """# HW 1B — Measurement judgment at Oak Street Lift Station

**SEIS 201 Unit 1 | Transfer homework | Suggested effort: 1.5–2 hours**

## Your role

You are supporting Diane Halvorsen, PE, and Wes Tanaka, EIT, at ACMEJOB.Ai.
Their client, Westfield Public Works, is preparing the fictional Oak Street Lift
Station for startup. FOREMAN v4.2 has reviewed standby pressure readings and
issued a PASS. Diane wants your independent engineering recommendation before
she accepts that disposition.

This is a transfer from the Otter Bend class case: use the same measurement
reasoning in a new system. Analyze this case's evidence independently rather
than repeating the class-case conclusion.

## Files provided

1. `sensors_startup.csv`
2. `FOREMAN_PASS_report.md`
3. `install_startup_note.md`

## Assignment

Prepare a concise technical memo to Diane and Wes. Show enough calculation or
tabulation that another engineer could check your work. Your memo must:

1. **Describe the measurements.** Summarize the center and spread of the data in
   a useful way. Report at least one range, scatter measure, or uncertainty
   consideration, and state what that quantity does—and does not—tell you.
2. **Check the requirement at the right level.** Identify the acceptance
   requirement and compare it with the observations. Do not assume that one
   overall average is the correct test merely because software reports it.
3. **Distinguish error types.** Explain what evidence would be consistent with
   random variation and what would be consistent with systematic error. Use
   “precision” and “accuracy” carefully.
4. **Make the call.** Decide whether FOREMAN's PASS is acceptable as written.
   If an average hides a material channel-level result, say so directly and
   refuse that reasoning. State any hold, check, correction, or retest you
   recommend and who owns final acceptance.
5. **Keep a decision log.** Record what you checked, what evidence you used,
   assumptions you made, tools or calculations you relied on, and what you did
   not or could not verify. Include unresolved questions rather than silently
   filling gaps.

Suggested decision-log columns:

| Time / step | Check or calculation | Evidence / file | Decision or finding | Not verified / next step |
|---|---|---|---|---|

## Submit

- One short engineering memo with your recommendation and supporting results.
- Your decision log (it may be appended to the memo).
- Any small analysis file or code needed to reproduce your numbers.

Clarity and engineering judgment matter more than elaborate formatting. Do not
alter or discard observations without documenting why.

---

**SCHEMATIC / INSTRUCTIONAL DATA ONLY.** Westfield Public Works, Oak Street Lift
Station, its specification, and all measurements are fictional. The materials
are not verified by a licensed engineer and are not suitable for design,
construction, operation, or public-safety decisions.
"""
    (STUDENT_DIR / "HW1B-student-ask.md").write_text(handout, encoding="utf-8")


def write_readme() -> None:
    readme = f"""# Instructor README — SEIS 201 Unit 1 HW Case B

This is the **transfer homework case** that follows the M02 class case. The class
case remains Otter Bend; this homework case is Oak Street Lift Station. Do not
assign this package before the M02 reveal.

## Scenario

ACMEJOB.Ai is supporting fictional client Westfield Public Works during startup
of the fictional Oak Street Lift Station. Diane Halvorsen, PE; Wes Tanaka, EIT;
and FOREMAN v4.2 return in a new setting. Eight discharge-pressure transducers
are checked under one defined no-flow standby condition.

The student package practices:

- measurement uncertainty and channel-to-channel comparison;
- random versus systematic error;
- precision versus accuracy;
- refusing a false average that hides a bad channel; and
- documenting a defensible decision log.

## Package layout

- `student/HW1B-student-ask.md` — one-page student handout and submission ask.
- `student/sensors_startup.csv` — 96 long-format readings (12 per channel).
- `student/FOREMAN_PASS_report.md` — automated PASS disposition.
- `student/install_startup_note.md` — field context and startup record.
- `instructor/INSTRUCTOR_KEY.md` — planted condition and expected analysis.

Keep `instructor/` out of any student ZIP or LMS release.

## Data provenance

The dataset is generated by
`tools/teaching-pack/generate_hw_case_b.py` with Python's deterministic
`random.Random` seed **{SEED}**. Re-running that script regenerates the CSV and
all quoted statistics.

All sites, organizations, specifications, and values are fictional,
schematic/instructional, and not verified by a licensed engineer. No artifact
is suitable for design, construction, operation, or public-safety decisions.
"""
    (OUTPUT_DIR / "README.md").write_text(readme, encoding="utf-8")


def write_instructor_key(
    readings: dict[str, list[float]], means: dict[str, float], grand_average: float
) -> None:
    good_channels = [
        value
        for channel, values in readings.items()
        if channel != PLANTED_CHANNEL
        for value in values
    ]
    good_average = statistics.mean(good_channels)
    planted_sd = statistics.stdev(readings[PLANTED_CHANNEL])
    diluted_bias = grand_average - good_average

    table_rows = "\n".join(
        f"| {channel} | {means[channel]:.3f} | "
        f"{means[channel] - BASELINE_PSIG:+.3f} | "
        f"{'FAIL' if abs(means[channel] - BASELINE_PSIG) > TOLERANCE_PSIG else 'PASS'} |"
        for channel in CHANNELS
    )

    key = f"""# Instructor key — HW Case B: Oak Street Lift Station

**Do not distribute with the student package.**

## Planted condition

- Bad channel: **{PLANTED_CHANNEL}**
- Planted systematic offset: **+{PLANTED_OFFSET_PSIG:.2f} psig**
- Expected standby baseline: **{BASELINE_PSIG:.2f} psig**
- Fictional requirement: WP-LS-3 §2.1, **each channel** within
  ±{TOLERANCE_PSIG:.2f} psig under the defined standby condition
- {PLANTED_CHANNEL} sample mean: **{means[PLANTED_CHANNEL]:.3f} psig**
- {PLANTED_CHANNEL} sample standard deviation: **{planted_sd:.3f} psig**

The bad channel's readings are tightly grouped, so the channel is **precise but
inaccurate**. The offset is systematic; its small reading-to-reading scatter is
random variation.

## Reproducible results

| Channel | Mean (psig) | Error from 42.00 (psig) | Per-channel result |
|---|---:|---:|---|
{table_rows}

The mean of all 96 observations is **{grand_average:.3f} psig** (FOREMAN rounds
to **{grand_average:.2f} psig**), or
**{grand_average - BASELINE_PSIG:+.3f} psig** versus the baseline. That numeric
calculation is correct.

The seven unaffected channels average **{good_average:.3f} psig**. Giving each
channel equal weight dilutes one channel's roughly +4.8 psig bias by a factor of
eight, leaving only about **{diluted_bias:+.3f} psig** in the grand average.
That falls inside ±0.75 psig even though {PLANTED_CHANNEL} itself fails badly.
FOREMAN applied an array-level average to a per-channel requirement, so its PASS
method and disposition are wrong.

## Buried clue

The technician-notes section of `install_startup_note.md` says a local zero trim
showing +4.8 psi correction was used on PT-107 while its equalization valve was
shut. Students should find this only after examining the data and then returning
to the field record. It supports, but does not replace, the statistical evidence
of systematic error.

## What a good student write-up includes

1. **Requirement:** quotes or paraphrases “each channel,” the 42.00 psig defined
   standby baseline, and the ±0.75 psig limit.
2. **Evidence:** calculates per-channel means and a scatter measure or range;
   identifies PT-107 as tight but high.
3. **Diagnosis:** distinguishes its random scatter from systematic offset and
   uses “precise but inaccurate” correctly.
4. **Judgment:** rejects FOREMAN's PASS even though its arithmetic is correct;
   explains why averaging across channels answers the wrong question.
5. **Action:** holds acceptance, checks PT-107 zero/manifold/configuration
   against a traceable reference, corrects or replaces it, and repeats the
   defined standby test for every channel. Students should not simply delete the
   outlier and proceed.
6. **Decision log:** records the requirement, dataset/version, calculations,
   anomaly, field-note clue, decision owner, hold/retest action, and unresolved
   uncertainty. Diane, not FOREMAN, owns engineering acceptance.

Reasonable uncertainty discussions may mention reference-gauge uncertainty,
resolution, repeatability, stabilization, and whether the ±0.75 psig criterion
is an acceptance limit rather than a statistical confidence interval.

---

Fictional instructional case. Data generated with seed {SEED}. Not verified by
a licensed engineer.
"""
    (INSTRUCTOR_DIR / "INSTRUCTOR_KEY.md").write_text(key, encoding="utf-8")


def main() -> None:
    STUDENT_DIR.mkdir(parents=True, exist_ok=True)
    INSTRUCTOR_DIR.mkdir(parents=True, exist_ok=True)

    readings = generate_readings()
    means = {
        channel: statistics.mean(values) for channel, values in readings.items()
    }
    grand_average = statistics.mean(
        value for values in readings.values() for value in values
    )

    write_csv(readings)
    write_foreman_report(grand_average)
    write_startup_note()
    write_student_ask()
    write_readme()
    write_instructor_key(readings, means, grand_average)

    print(f"Wrote HW Case B artifacts to {OUTPUT_DIR}")
    for channel in CHANNELS:
        print(f"{channel}: mean={means[channel]:.3f} psig")
    print(f"Grand average: {grand_average:.3f} psig")


if __name__ == "__main__":
    main()
